"""Rename created_at to requested_at in DocumentRequest

Revision ID: c1b07e7d4f76
Revises: 4622b6c4f1c1
Create Date: 2024-11-19 07:57:45.883460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b07e7d4f76'
down_revision = '4622b6c4f1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('requested_at')

    # ### end Alembic commands ###
