name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create minimal deployment package
      run: |
        # Create a clean directory for deployment files
        mkdir deploy_temp
        
        # Copy only the essential files
        cp -r app deploy_temp/
        cp -r migrations deploy_temp/
        cp requirements.txt deploy_temp/
        cp config.py deploy_temp/
        cp application.py deploy_temp/
        
        # Create startup script
        cat > deploy_temp/startup.sh << 'EOL'
        #!/bin/bash
        cd /home/site/wwwroot
        python -m venv antenv
        source antenv/bin/activate
        pip install -r requirements.txt
        gunicorn --bind=0.0.0.0:8000 application:app
        EOL
        chmod +x deploy_temp/startup.sh
        
        # Create deployment config
        echo "[config]" > deploy_temp/.deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> deploy_temp/.deployment

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'HealthBridge'
        package: deploy_temp

    - name: Cleanup
      if: always()
      run: rm -rf deploy_temp
