name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create deployment package
      run: |
        # Create a clean deployment directory
        mkdir deploy_package
        
        # Copy only necessary files
        cp -r \
          app \
          migrations \
          requirements.txt \
          config.py \
          application.py \
          startup.sh \
          .deployment \
          deploy_package/
        
        # Create startup script
        echo "#!/bin/bash" > deploy_package/startup.sh
        echo "cd /home/site/wwwroot" >> deploy_package/startup.sh
        echo "python -m venv antenv" >> deploy_package/startup.sh
        echo "source antenv/bin/activate" >> deploy_package/startup.sh
        echo "pip install -r requirements.txt" >> deploy_package/startup.sh
        echo "gunicorn --bind=0.0.0.0:8000 application:app" >> deploy_package/startup.sh
        chmod +x deploy_package/startup.sh
        
        # Create deployment config
        echo "[config]" > deploy_package/.deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> deploy_package/.deployment
        
        # Create archive
        cd deploy_package
        zip -r ../deploy.zip .

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'HealthBridge'
        package: deploy.zip

    - name: Upload artifact for debugging (optional)
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: deploy.zip
