name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment files
      run: |
        echo "#!/bin/bash" > startup.sh
        echo "cd /home/site/wwwroot" >> startup.sh
        echo "source antenv/bin/activate" >> startup.sh
        echo "gunicorn --bind=0.0.0.0:8000 application:app" >> startup.sh
        chmod +x startup.sh
        
        echo "[config]" > .deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment

    - name: Prepare deployment package
      run: |
        mkdir deploy
        cp -r * deploy/ 2>/dev/null || true
        cp -r .* deploy/ 2>/dev/null || true
        cd deploy
        rm -rf .git antenv __pycache__ .pytest_cache .coverage htmlcov *.log *.pyc 2>/dev/null || true

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'HealthBridge'
        package: deploy

    - name: Cleanup
      if: always()
      run: |
        rm -rf deploy
